name: Flutter Release

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: "3.3.0"

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get

    - name: Clean Flutter
      run: flutter clean

    - name: Build Web
      run: flutter build web --release

    - name: Build Android (APK)
      run: flutter build apk --release

    - name: Verify Android APK exists
      run: |
        test -f build/app/outputs/apk/release/app-release.apk || { echo "APK not found. Check Flutter build output path."; exit 1; }
        cp build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/itm-connect.apk

    # - name: Build iOS (IPA)
    #   run: flutter build ipa --no-codesign

    - name: Generate Version Number
      id: vars
      run: echo "version=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

    - name: Zip Web Build
      run: zip -r web_build.zip build/web

    - name: Ensure 'latest' release exists (or update it)
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: ITM Connect — Latest
        draft: false
        prerelease: false
        generate_release_notes: false
        body: |
          This is the stable rolling release. Assets here are kept up to date with the latest successful build from main.
          Commit: ${{ github.sha }}
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Replace assets on 'latest' (web + apk)
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: |
          web_build.zip
          build/app/outputs/apk/release/itm-connect.apk
        file_glob: false
        overwrite: true
        asset_name: |
          ITM-Connect-Web.zip
          ITM-Connect.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create archival release v${{ steps.vars.outputs.version }} (attach web)
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.vars.outputs.version }}
        name: ITM Connect — v${{ steps.vars.outputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: false
        body: |
          Release generated from commit ${{ github.sha }}
        files: |
          web_build.zip
        file_glob: false
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Android Artifact to archival v${{ steps.vars.outputs.version }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.vars.outputs.version }}
        files: |
          build/app/outputs/apk/release/itm-connect.apk
        file_glob: false
        overwrite: true
        asset_name: ITM-Connect-v${{ steps.vars.outputs.version }}.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Upload iOS Artifact to archival v${{ steps.vars.outputs.version }}
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     tag_name: v${{ steps.vars.outputs.version }}
    #     files: |
    #       build/ios/ipa/runner.ipa#runner.ipa
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
